---
# tasks file for openldap consumer sync

- name: Create OpenLDAP consumer sync LDIF
  template: >
    src=consumer_sync.ldif.j2
    dest=/root/openldap/consumer_sync.ldif
    owner=root
    group=root
    mode=0644
  tags:
    - openldap
    - sync

- name: Enable OpenLDAP consumer sync
  command: ldapadd -Q -Y EXTERNAL -H ldapi:/// -f /root/openldap/consumer_sync.ldif
  tags:
    - openldap
    - sync
