---
# tasks file for openldap

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: openldap

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: openldap

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: openldap

- name: Create OpenLDAP LDIF configuration directory
  file: >
    path=/root/openldap
    owner=root
    group=root
    mode=0750
    state=directory
  tags: openldap

- include: consumer_sync.yml
  when: openldap_sync_consumer
  tags: openldap
