---
# tasks file for openldap

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: openldap

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: openldap

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: openldap

- include: consumer_sync.yml
  when: openldap_sync
  tags: openldap
