---
# tasks file for openldap

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: openldap

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: openldap

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: openldap

- name: Create OpenLDAP LDIF configuration directory
  file: >
    path=/root/openldap
    owner=root
    group=root
    mode=0750
    state=directory
  tags: openldap

- name: Load OpenLDAP schemas
  command: ldapadd -Y EXTERNAL -H ldapi:// -f /etc/ldap/schema/{{ item }}.ldif
  with_items:
    - corba
    - dyngroup
    - inetorgperson
    - java
    - misc
    - nis
    - openldap
    - ppolicy
  tags: openldap

- include: consumer_sync.yml
  when: openldap_sync_consumer
  tags: openldap
